name: deploy-py-lambda
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@main
    - name: Deploy code to Lambda
      uses: kohrongying/py-lambda-action@v1.0.2
      with:
        lambda_layer_arn: 'arn:aws:lambda:us-east-2:634124042701:function:hello-world-python'
        lambda_function_name: 'hello-world-python'
        exclude_files: 'tests my-other-file.txt'
        lambda_layer_publish: true
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'us-east-2'
